#压力测试配置
threadCount: 100
requestCount: 100

#api测试配置
api:
  apiClassPath: C:\javaSourceCode\testapi\target
#  className: org.simple.invoke.api.DefaultTestApi
  className: org.simple.App
  args: hello

#http测试配置
http:
#  url: http://localhost:18888/system/role/list
#  method: get
#  args: "{\"userCode\":\"admin\",\"password\":\"admin\"}"
#  successResult: "{\"code\":0"
##  successResult: "{\"code\":0,\"msg\":null,\"data\":null}"
#  contain: true